
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MULT = 37;
  public static final int CAPIROTE = 34;
  public static final int LIT_REAL = 32;
  public static final int RESTA = 36;
  public static final int PORCENTAJE = 39;
  public static final int INT = 4;
  public static final int LLAVE_C = 25;
  public static final int LLAVE_A = 24;
  public static final int LIT_CADENA = 30;
  public static final int DELETE = 11;
  public static final int WRITE = 13;
  public static final int NOT = 49;
  public static final int AND = 47;
  public static final int MENORIGUAL = 44;
  public static final int MAYORQUE = 43;
  public static final int TYPE = 15;
  public static final int OR = 48;
  public static final int NOIGUAL_COMP = 41;
  public static final int BOOL = 2;
  public static final int ARROBA = 28;
  public static final int CALL = 16;
  public static final int DIV = 38;
  public static final int SUMA = 35;
  public static final int IF = 6;
  public static final int AMPERSAND = 27;
  public static final int MAYORIGUAL = 45;
  public static final int PUNTYCOMA = 20;
  public static final int EOF = 0;
  public static final int TRUE = 51;
  public static final int DOBLEAMPERSAND = 26;
  public static final int IGUAL_OP = 46;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int NULL = 50;
  public static final int PAR_C = 19;
  public static final int PAR_A = 18;
  public static final int MENORQUE = 42;
  public static final int REAL = 3;
  public static final int ELSE = 7;
  public static final int PUNTO = 22;
  public static final int NL = 14;
  public static final int READ = 12;
  public static final int IDEN = 29;
  public static final int WHILE = 8;
  public static final int IGUAL_COMP = 40;
  public static final int LIT_ENTERO = 31;
  public static final int PROC = 17;
  public static final int STRING = 5;
  public static final int FALSE = 52;
  public static final int STRUCT = 9;
  public static final int CORCH_C = 21;
  public static final int CORCH_A = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "REAL",
  "INT",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "STRUCT",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "TYPE",
  "CALL",
  "PROC",
  "PAR_A",
  "PAR_C",
  "PUNTYCOMA",
  "CORCH_C",
  "PUNTO",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "DOBLEAMPERSAND",
  "AMPERSAND",
  "ARROBA",
  "IDEN",
  "LIT_CADENA",
  "LIT_ENTERO",
  "LIT_REAL",
  "CORCH_A",
  "CAPIROTE",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "PORCENTAJE",
  "IGUAL_COMP",
  "NOIGUAL_COMP",
  "MENORQUE",
  "MAYORQUE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "IGUAL_OP",
  "AND",
  "OR",
  "NOT",
  "NULL",
  "TRUE",
  "FALSE"
  };
}

