package alexTiny0;

public enum ClaseLexica {
    INT, BOOL, AND, OR, NOT, NULL, TRUE, FALSE,
    IDEN, ENT, REAL, IGUAL,
    MAS, MENOS, POR, DIV, EVALUA, DONDE, EOF,
    MENORQUE, MAYORQUE, MENORIGUAL, MAYORIGUAL,
    IGUAL_COMP, NOIGUAL_COMP, PAR_APERTURA, PAR_CIERRE, PUNTOYCOMA,
    LLAVE_APERTURA, LLAVE_CIERRE, DOBLEAMPERSAND, ARROBA
}