package alex;

public enum ClaseLexica {
    INT,REAL,BOOL,STRING,AND,OR,NOT,NULL,TRUE,
    FALSE,PROC,IF,ELSE,WHILE,STRUCT,NEW,DELETE,
    READ,WRITE,NL,TYPE,CALL,SUMA,RESTA,MULT,DIV,
    PORCENTAJE,MENORQUE,MAYORQUE,MENORIGUAL,MAYORIGUAL,
    IGUAL_COMP,NOIGUAL_COMP,PAR_A,PAR_C,PUNTOYCOMA,IGUAL_OP,
    CORCH_A,CORCH_C,PUNTO,CAPIROTE,COMA,LLAVE_A,LLAVE_C,AMPERSAND,DOBLEAMPERSAND,
    ARROBA,DIGPOSITIVO,DIGITO,PARTEENTERA,LITENTERO,PARTEDECIMAL,PARTEEXPONENCIAL,
    SEGPARTEREAL,LITREAL,LETRA,CARACTER,IDEN,LITCADENA, EOF
}
